#!/bin/sh
if [ "$SKIP_AZURE_SYNC" = "1" ]; then exit 0; fi
powershell -NoProfile -ExecutionPolicy Bypass -File "$(dirname "$0")/../scripts/deploy-dev.ps1" -Source "$(dirname "$0")/../src" -AccountName "pdvstatic" -Container '$web'
